name: 'fusionnet'
logdir: 'logger/fusionnet/'
model-type: 'fusion'

lr: 3e-5
epoch: 50
seq-length: 50
batch-size: 16
num-workers: 5
write-freq: 100
joint-type: 'COCO17'
sex: 'neutral'

keypoints-noise: 8e-3
calib-noise: 0.15
  
lw-kp3d: 1e3
lw-pose: 5e1
lw-betas: 5e-2

supervise-unimodal-until-n-epoch: 5
drop-rate: 0.1
attn-drop-rate: 0.
attn-drop-path-rate: 0.1